# Generated by Django 5.1.7 on 2025-06-03 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_livro_capa'),
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='foto',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='uploader.image'),
        ),
    ]
